config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :mesas
  
    root :to =>"mesas#index"

end

app/models/mesa.rb
class Mesa < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # : :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mesas_controller.rb
class MesasController < ApplicationController
  
  before_filter :authenticate_user!
  
  before_action :set_mesa, only: [:show, :edit, :update, :destroy]

  # GET /mesas
  # GET /mesas.json
  def index
    @mesas = Mesa.all
  end

  # GET /mesas/1
  # GET /mesas/1.json
  def show
  end

  # GET /mesas/new
  def new
    @mesa = Mesa.new
  end

  # GET /mesas/1/edit
  def edit
  end

  # POST /mesas
  # POST /mesas.json
  def create
    @mesa = Mesa.new(mesa_params)

    respond_to do |format|
      if @mesa.save
        format.html { redirect_to @mesa, notice: 'Mesa was successfully created.' }
        format.json { render :show, status: :created, location: @mesa }
      else
        format.html { render :new }
        format.json { render json: @mesa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mesas/1
  # PATCH/PUT /mesas/1.json
  def update
    respond_to do |format|
      if @mesa.update(mesa_params)
        format.html { redirect_to mesas_path, notice: 'Check-in Realizado com Sucesso' }
        format.json { render :show, status: :ok, location: @mesa }
      else
        format.html { render :edit }
        format.json { render json: @mesa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mesas/1
  # DELETE /mesas/1.json
  def destroy
    @mesa.destroy
    respond_to do |format|
      format.html { redirect_to mesas_url, notice: 'Mesa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mesa
      @mesa = Mesa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mesa_params
      params.require(:mesa).permit(:c_mesa, :c_user, :n_user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mesas_helper.rb
module MesasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Login</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  
<%= yield %>

</body>
</html>

app/views/mesas/_form.html.erb
<%= form_for(@mesa) do |f| %>
  <% if @mesa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mesa.errors.count, "error") %> prohibited this mesa from being saved:</h2>

      <ul>
      <% @mesa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Codigo_Mesa %><br>
    <%= f.text_field :c_mesa ,readonly: true %>
  </div>

  <div class="field">
    <%= f.label :Nome_Usuario %><br>
    <%= f.text_field :n_user %>
  </div>
  <div class="actions">
    <%= f.submit "Check-in"%>
  </div>
<% end %>

app/views/mesas/edit.html.erb
<h1>Realizando Check-in</h1>

<%= render 'form' %>

app/views/mesas/index.html.erb
<h1>9o. Andar E-Business Park</h1>

<table>
  <thead>
    <tr>
      <th>Codigo Mesa</th>
      <th>Nome Usuario</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @mesas.each do |mesa| %>
      <tr>
        <td><%= mesa.c_mesa %></td>
        <td><%= mesa.n_user %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/mesas/new.html.erb
<h1>New mesa</h1>

<%= render 'form' %>

<%= link_to 'Back', mesas_path %>

app/views/mesas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>C mesa:</strong>
  <%= @mesa.c_mesa %>
</p>

<p>
  <strong>C user:</strong>
  <%= @mesa.c_user %>
</p>

<p>
  <strong>N user:</strong>
  <%= @mesa.n_user %>
</p>

<%= link_to 'Edit', edit_mesa_path(@mesa) %> |
<%= link_to 'Back', mesas_path %>